# Generated by Django 5.2.7 on 2026-02-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('commission', 'Commission')], max_length=20),
        ),
    ]
