# Generated by Django 5.2.7 on 2026-07-04 19:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('swap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sl', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt5_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MT5 Position',
                'verbose_name_plural': 'MT5 Positions',
                'ordering': ['-opened_at'],
            },
        ),
    ]
