# Generated by Django 5.2.7 on 2026-07-07 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_kyc_status_user_kyc_submitted_at_kycsubmission'),
        ('mt5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5position',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mt5_positions', to='accounts.account'),
        ),
    ]
