# Generated by Django 5.2.7 on 2026-04-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementrequest',
            name='started_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
