# Generated by Django 5.2.7 on 2026-04-07 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCareSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_music', models.FileField(blank=True, help_text='Soft background song played while user waits', null=True, upload_to='customercare/hold_music/')),
                ('welcome_audio', models.FileField(blank=True, help_text='Voice message: Welcome to TradeRiser...', null=True, upload_to='customercare/welcome/')),
                ('welcome_text', models.TextField(default='Welcome to TradeRiser Customercare. You will be served by the next available agent.', help_text='Text shown to user while waiting')),
            ],
            options={
                'verbose_name_plural': 'Customer Care Settings',
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('voice_preset', models.CharField(choices=[('default', 'Default Voice'), ('lady', 'Lady Voice'), ('child', 'Child Voice')], default='default', max_length=20)),
                ('recording', models.FileField(blank=True, null=True, upload_to='customercare/recordings/')),
                ('is_missed', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_calls', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='customercare.chatthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
