# Generated by Django 5.2.7 on 2026-04-12 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0002_customercaresettings_callsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Plain text message')),
                ('html_message', models.TextField(blank=True, help_text='Optional HTML version (for beautiful emails)', null=True)),
                ('recipient_type', models.CharField(choices=[('single', 'Single User (Private)'), ('all', 'All Users (Broadcast)')], default='single', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_admin_emails', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text="Only used when recipient_type = 'single'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_admin_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Email',
                'verbose_name_plural': 'Admin Emails',
                'ordering': ['-sent_at'],
            },
        ),
    ]
