# Generated by Django 5.2.7 on 2026-04-12 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0003_adminemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminemail',
            name='html_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminemail',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_admin_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
