# Generated by Django 5.2.7 on 2026-09-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agentdeposit_account_and_more'),
        ('customercare', '0004_alter_adminemail_html_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='current_agent',
            field=models.ForeignKey(blank=True, help_text='The agent this user is currently chatting with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_chats', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='message',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='If this message is sent as a specific agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='agents.agent'),
        ),
    ]
