# Generated by Django 5.2.7 on 2026-06-08 07:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='max_allocation',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Maximum amount a user can allocate to copy you', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00')), django.core.validators.MaxValueValidator(Decimal('5000.00'))]),
        ),
        migrations.AlterField(
            model_name='trader',
            name='min_allocation',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum amount a user can allocate to copy you (e.g. 10 USD)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))]),
        ),
    ]
