# Generated by Django 5.2.7 on 2026-06-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mpesa_simulator', '0008_alter_mpesatransaction_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('received', 'Received Money'), ('sent', 'Sent Money')], max_length=10)),
                ('message', models.TextField()),
                ('caller_id', models.CharField(default='MPESA', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mpesa_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='mpesa_simulator.mpesatransaction')),
                ('mpesa_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mpesa_simulator.mpesauser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
