# Generated by Django 5.2.7 on 2026-08-24 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_message_notification', '0001_initial'),
        ('mpesa_simulator', '0010_mpesatransaction_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesanotification',
            name='equity_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mpesanotification',
            name='source',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('equity', 'Equity Bank')], default='mpesa', max_length=10),
        ),
        migrations.AddField(
            model_name='mpesanotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equity_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mpesanotification',
            name='caller_id',
            field=models.CharField(default='MPESA', max_length=30),
        ),
        migrations.AlterField(
            model_name='mpesanotification',
            name='mpesa_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mpesa_simulator.mpesauser'),
        ),
    ]
