# Generated by Django 5.2.7 on 2026-06-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='binance_address',
            field=models.CharField(blank=True, help_text='Binance wallet address (USDT, BEP20, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentdeposit',
            name='binance_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction ID / Tx Hash from Binance', max_length=100, null=True, verbose_name='Binance Transaction Hash'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('binance', 'Binance')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('binance', 'Binance')], db_index=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='agentwithdrawal',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('binance', 'Binance')], db_index=True, editable=False, max_length=30),
        ),
    ]
