# Generated by Django 5.2.7 on 2026-06-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_binance_address_agentdeposit_binance_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentwithdrawal',
            name='user_binance_address',
            field=models.CharField(blank=True, help_text="User's Binance wallet address to receive withdrawal (USDT BEP20 recommended)", max_length=100, null=True),
        ),
    ]
