# Generated by Django 5.2.7 on 2026-09-05 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_kycsubmission_id_document_and_more'),
        ('agents', '0003_agentwithdrawal_user_binance_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdeposit',
            name='account',
            field=models.ForeignKey(limit_choices_to={'account_type__in': ['standard', 'pro-fx', 'mt5']}, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='agentwithdrawal',
            name='account',
            field=models.ForeignKey(limit_choices_to={'account_type__in': ['standard', 'pro-fx', 'mt5']}, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
    ]
