# trading/urls.py
from django.urls import path
from .views import (
    MarketListView,
    TradeTypeListView,
    RobotListView,
    PurchaseRobotView,
    UserRobotListView,
    PlaceTradeView,
    TradeHistoryView,
    ResetDemoBalanceView,
    GenerateSignalView,
    PlaceDigitTradeView,
    PlaceSRobotTradeView,
    PlaceBulkTradeView, 
    EliteConfigView,
    EliteValidateCodeView,
    EliteStartRunView,
    EliteRunStatusView,
    EliteResetView,
    EliteStopView,
    EliteUpgradeView,
)

urlpatterns = [
    path('markets/', MarketListView.as_view(), name='market_list'),
    path('trade-types/', TradeTypeListView.as_view(), name='trade_type_list'),
    path('robots/', RobotListView.as_view(), name='robot_list'),
    path('robots/<int:robot_id>/purchase/', PurchaseRobotView.as_view(), name='purchase_robot'),
    path('user-robots/', UserRobotListView.as_view(), name='user_robot_list'),
    path('trades/place/', PlaceTradeView.as_view(), name='place_trade'),
    path('trades/history/', TradeHistoryView.as_view(), name='trade_history'),
    path('reset-demo-balance/', ResetDemoBalanceView.as_view(), name='reset_demo_balance'),
    path('signals/generate/', GenerateSignalView.as_view(), name='generate_signal'),
    path('trades/place-digit/', PlaceDigitTradeView.as_view(), name='place_digit_trade'),
    path('trades/place-srobot/', PlaceSRobotTradeView.as_view(), name='place_srobot_trade'),
    # NEW: Bulk Trades AI Endpoint
    path('trades/place-bulk/', PlaceBulkTradeView.as_view(), name='place_bulk_trade'),
    path('elite/config/', EliteConfigView.as_view(), name='elite_config'),
    path('elite/validate-code/', EliteValidateCodeView.as_view(), name='elite_validate_code'),
    path('elite/start/', EliteStartRunView.as_view(), name='elite_start'),
    path('elite/status/', EliteRunStatusView.as_view(), name='elite_status'),
    path('elite/reset/', EliteResetView.as_view(), name='elite_reset'),
    path('elite/stop/', EliteStopView.as_view(), name='elite_stop'),
    path('elite/upgrade/', EliteUpgradeView.as_view(), name='elite_upgrade'),
]