# Generated by Django 5.2.7 on 2026-03-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deriv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivuseraccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='derivuseraccount',
            name='access_token',
            field=models.TextField(help_text='OAuth Bearer token'),
        ),
    ]
