# Generated by Django 5.2.7 on 2026-02-18 00:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('pip_value', models.DecimalField(decimal_places=5, default=Decimal('0.0001'), max_digits=10)),
                ('contract_size', models.IntegerField(default=100000)),
                ('spread', models.DecimalField(decimal_places=5, default=Decimal('0.0001'), max_digits=10)),
                ('base_simulation_price', models.DecimalField(decimal_places=5, default=Decimal('1.1000'), max_digits=10)),
                ('default_time_frame', models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '24 Hours')], default='M1', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ForexRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='robots/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='If set, this discounted price will be used instead of the original price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('best_markets', models.CharField(choices=[('forex', 'Forex'), ('crypto', 'Crypto'), ('indices', 'Indices'), ('commodities', 'Commodities')], max_length=20)),
                ('win_rate_sashi', models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('win_rate_normal', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stake_per_trade', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Default stake per trade (can be overridden by user)', max_digits=10)),
                ('profit_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Profit = stake × multiplier on win (e.g., 2.00 = 2:1 RR)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('volume_lots', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=5)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sl', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('floating_p_l', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('leverage', models.IntegerField(default=500)),
                ('time_frame', models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '24 Hours')], default='M1', max_length=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forex_positions', to='accounts.account')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forex.forexpair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forex_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='ForexTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('realized_p_l', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_reason', models.CharField(max_length=10)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forex.position')),
            ],
        ),
        migrations.CreateModel(
            name='UserRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_running', models.BooleanField(default=False)),
                ('last_trade_time', models.DateTimeField(blank=True, null=True)),
                ('stake_per_trade', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Stake amount per trade (overrides robot default)', max_digits=10)),
                ('timeframe', models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '24 Hours')], default='M1', help_text='Chart timeframe for simulation', max_length=3)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.forexrobot')),
                ('selected_pair', models.ForeignKey(blank=True, help_text='Pair to trade (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forex.forexpair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'robot')},
            },
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('trade_result', models.CharField(blank=True, max_length=10, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='forex.userrobot')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
