# Generated by Django 5.2.7 on 2026-04-13 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexrobot',
            name='is_ea',
            field=models.BooleanField(default=False, help_text='If True, this robot acts as a real EA: opens actual Positions, manages multiple trades, auto-closes profitable ones'),
        ),
        migrations.AddField(
            model_name='forexrobot',
            name='max_open_positions',
            field=models.IntegerField(default=2, help_text='Maximum number of concurrent open positions for this EA', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='userrobot',
            name='is_ea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrobot',
            name='max_open_positions',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userrobot',
            name='target_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: EA will automatically stop when wallet balance reaches this target', max_digits=12, null=True),
        ),
    ]
