# Generated by Django 5.2.7 on 2026-04-13 12:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_forexrobot_is_ea_forexrobot_max_open_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forexrobot',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='forexrobot',
            name='is_ea',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forexrobot',
            name='max_open_positions',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='forexrobot',
            name='profit_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='forexrobot',
            name='stake_per_trade',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='forextrade',
            name='close_reason',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='forextrade',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='forex.position'),
        ),
        migrations.AlterField(
            model_name='userrobot',
            name='selected_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forex.forexpair'),
        ),
        migrations.AlterField(
            model_name='userrobot',
            name='stake_per_trade',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='userrobot',
            name='target_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userrobot',
            name='timeframe',
            field=models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '24 Hours')], default='M1', max_length=3),
        ),
    ]
