# Generated by Django 5.2.7 on 2026-04-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0003_position_close_price_position_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='ea_robot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_positions', to='forex.userrobot'),
        ),
    ]
