# Generated by Django 5.2.7 on 2026-02-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesauser',
            name='profile_photo',
            field=models.URLField(blank=True, default='https://example.com/default-avatar.jpg', null=True),
        ),
    ]
