# Generated by Django 5.2.7 on 2026-02-21 12:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_simulator', '0002_mpesauser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesauser',
            name='fuliza',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
