# Generated by Django 5.2.7 on 2026-02-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_simulator', '0003_mpesauser_fuliza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesauser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mpesa_avatars/%Y/%m/%d/'),
        ),
    ]
