# Generated by Django 5.2.7 on 2026-02-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_simulator', '0004_alter_mpesauser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
