# Generated by Django 5.2.7 on 2026-02-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_simulator', '0005_mpesatransaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='category',
            field=models.CharField(blank=True, choices=[('family_friends', 'Family and Friends'), ('business', 'Business'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
