# Generated by Django 5.2.7 on 2026-02-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_simulator', '0006_mpesatransaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='mpesa_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
