# Generated by Django 5.2.7 on 2026-02-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_simulator', '0007_mpesatransaction_mpesa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
