# Generated by Django 5.2.7 on 2026-06-13 18:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_simulator', '0008_alter_mpesatransaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesauser',
            name='daily_limit_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mpesauser',
            name='daily_sent_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
