# Generated by Django 5.2.7 on 2026-06-16 12:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_simulator', '0009_mpesauser_daily_limit_reset_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
