# Generated by Django 5.2.7 on 2026-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AddField(
            model_name='account',
            name='is_wallet_verified',
            field=models.BooleanField(default=True, help_text='Uncheck this to block withdrawals and internal transfers for this account. New accounts are automatically verified.', verbose_name='Wallet Verified'),
        ),
    ]
