# Generated by Django 5.2.7 on 2026-04-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_account_is_wallet_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_wallet_verified',
            field=models.BooleanField(default=True, help_text='Uncheck this to block withdrawals and internal transfers for this account.', verbose_name='Wallet Verified'),
        ),
    ]
