# Generated by Django 5.2.7 on 2026-04-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_is_wallet_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_wallet_verified',
            field=models.BooleanField(default=True, help_text='Uncheck this to block withdrawals and internal transfers.', verbose_name='Wallet Verified'),
        ),
        migrations.AlterField(
            model_name='suspensionevidence',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
