# Generated by Django 5.2.7 on 2026-07-07 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_is_wallet_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 7, 13, 13, 26, 311391, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='deriv_login',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='deriv_server',
            field=models.CharField(blank=True, default='green.derivws.com', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='deriv_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='mt5_login',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='mt5_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='mt5_server',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='platform',
            field=models.CharField(choices=[('traderiser', 'Traderiser'), ('mt5', 'MT5'), ('deriv', 'Deriv')], default='traderiser', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('standard', 'TradeRiser Standard'), ('pro', 'TradeRiser Pro'), ('islamic', 'TradeRiser Islamic'), ('options', 'TradeRiser Options'), ('crypto', 'TradeRiser Crypto'), ('demo', 'TradeRiser Demo'), ('pro-fx', 'TradeRiser Pro-FX'), ('mt5', 'MT5 Real'), ('mt5-demo', 'MT5 Demo'), ('deriv', 'Deriv Real'), ('deriv-demo', 'Deriv Demo')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'platform', 'account_type')},
        ),
    ]
