# Generated by Django 5.2.7 on 2026-07-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_options_alter_account_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('standard', 'TradeRiser Standard'), ('pro', 'TradeRiser Pro'), ('islamic', 'TradeRiser Islamic'), ('options', 'TradeRiser Options'), ('crypto', 'TradeRiser Crypto'), ('demo', 'TradeRiser Demo'), ('pro-fx', 'TradeRiser Pro-FX'), ('mt5', 'MT5')], max_length=50),
        ),
    ]
