# Generated by Django 5.2.7 on 2026-07-07 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_options_alter_account_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.FileField(upload_to='kyc/id/%Y/%m/%d/')),
                ('selfie', models.FileField(upload_to='kyc/selfie/%Y/%m/%d/')),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to='kyc/address/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
