# Generated by Django 5.2.7 on 2026-07-24 10:10

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_kyc_status_user_kyc_submitted_at_kycsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmission',
            name='id_document',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='kyc/id/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='kyc/address/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='selfie',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='kyc/selfie/%Y/%m/%d/'),
        ),
    ]
