# Generated by Django 5.2.7 on 2026-07-04 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='account',
            name='is_wallet_verified',
            field=models.BooleanField(default=True, verbose_name='Wallet Verified'),
        ),
        migrations.AlterField(
            model_name='account',
            name='platform',
            field=models.CharField(choices=[('traderiser', 'Traderiser'), ('mt5', 'MT5'), ('deriv', 'Deriv')], default='traderiser', max_length=20),
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.FileField(upload_to='kyc/id_documents/%Y/%m/%d/')),
                ('selfie', models.FileField(upload_to='kyc/selfies/%Y/%m/%d/')),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to='kyc/proof_of_address/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
