# Generated by Django 5.2.7 on 2026-04-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='deriv_access_key',
            field=models.CharField(blank=True, help_text='Secret access key for Deriv bot. Only fill for Deriv Premium Robots.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='is_deriv_robot',
            field=models.BooleanField(default=False, help_text='Check this if this is a Deriv Premium Robot (provides access key only)'),
        ),
    ]
