# Generated by Django 5.2.7 on 2026-04-18 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_account_is_wallet_verified'),
        ('trading', '0003_trade_digit_market_type_trade_digit_prediction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='market',
            name='display_name',
            field=models.CharField(blank=True, help_text="Nice name shown to users, e.g. 'Volatility 75 (1s)'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='volatility_index',
            field=models.IntegerField(blank=True, help_text='e.g. 10, 25, 50, 75, 100 — used for Volatility (1s) indices', null=True),
        ),
        migrations.AddField(
            model_name='markettype',
            name='supports_digits',
            field=models.BooleanField(default=False, help_text='Enable this for Volatility markets that support digit (Over/Under, Even/Odd, Matches, Differs)'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='direction',
            field=models.CharField(choices=[('buy', 'Buy/Rise/Call'), ('sell', 'Sell/Fall/Put'), ('over', 'Over'), ('under', 'Under'), ('even', 'Even'), ('odd', 'Odd'), ('match', 'Matches'), ('differ', 'Differs')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='current_spot',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='digit_prediction',
            field=models.IntegerField(blank=True, help_text='0-9 for prediction in Over/Under or Matches', null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(choices=[('buy', 'Buy/Rise/Call'), ('sell', 'Sell/Fall/Put'), ('over', 'Over'), ('under', 'Under'), ('even', 'Even'), ('odd', 'Odd'), ('match', 'Matches'), ('differ', 'Differs')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_spot',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_spot',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='expiry_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds or ticks (1 tick = 1s for digits)', null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='last_digit_result',
            field=models.IntegerField(blank=True, help_text='Actual last digit at settlement', null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='volatility_index',
            field=models.IntegerField(blank=True, help_text='e.g. 10, 25, 50, 75, 100 — higher = faster movement', null=True),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['is_binary', 'digit_market_type'], name='trading_tra_is_bina_66b252_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'timestamp'], name='trading_tra_user_id_da151c_idx'),
        ),
    ]
