# Generated by Django 5.2.7 on 2026-04-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_auto_20260418_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='trade',
            name='trading_tra_is_bina_66b252_idx',
        ),
        migrations.RemoveIndex(
            model_name='trade',
            name='trading_tra_user_id_da151c_idx',
        ),
        migrations.RemoveField(
            model_name='market',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='market',
            name='volatility_index',
        ),
        migrations.RemoveField(
            model_name='markettype',
            name='supports_digits',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='digit_market_type',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='digit_prediction',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='expiry_seconds',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='is_binary',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='last_digit_result',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='volatility_index',
        ),
        migrations.AlterField(
            model_name='signal',
            name='direction',
            field=models.CharField(choices=[('buy', 'Buy/Rise/Touch'), ('sell', 'Sell/Fall/No Touch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='current_spot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(choices=[('buy', 'Buy/Rise/Touch'), ('sell', 'Sell/Fall/No Touch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_spot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_spot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
