# Generated by Django 5.2.7 on 2026-04-18 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_trade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='digit_barrier',
            field=models.PositiveIntegerField(blank=True, help_text='Barrier digit 0-9 for Over/Under/Matches', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='trade',
            name='digit_contract_type',
            field=models.CharField(blank=True, choices=[('matches', 'Matches'), ('differs', 'Differs'), ('even', 'Even'), ('odd', 'Odd'), ('over', 'Over'), ('under', 'Under')], help_text='matches, differs, even, odd, over, under', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='is_digit_trade',
            field=models.BooleanField(default=False, help_text='True if this is a digit (S Digit) trade'),
        ),
        migrations.AddField(
            model_name='trade',
            name='last_digit_outcome',
            field=models.PositiveIntegerField(blank=True, help_text='The actual last digit that appeared (0-9)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='is_deriv_robot',
            field=models.BooleanField(default=False, help_text='Check this if this is a Deriv Premium Robot'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(blank=True, choices=[('buy', 'Buy/Rise/Touch'), ('sell', 'Sell/Fall/No Touch')], max_length=10, null=True),
        ),
    ]
