# Generated by Django 5.2.7 on 2026-04-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_trade_digit_barrier_trade_digit_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='volatility_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
