# Generated by Django 5.2.7 on 2026-04-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_market_display_name_market_volatility_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='default_digit_contract_type',
            field=models.CharField(blank=True, choices=[('matches', 'Matches'), ('differs', 'Differs'), ('even', 'Even'), ('odd', 'Odd'), ('over', 'Over'), ('under', 'Under')], help_text='Optional default contract type for this robot (over, under, matches, etc.)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='is_s_digit_robot',
            field=models.BooleanField(default=False, help_text='This is an S-Digit Robot (uses strong Sashi bias: 90% for sashi users)'),
        ),
    ]
