# Generated by Django 5.2.7 on 2026-07-24 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_robot_default_digit_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_bulk_robot',
            field=models.BooleanField(default=False, help_text='This is a Bulk Trades AI Robot (can place multiple trades in one request)'),
        ),
        migrations.AddField(
            model_name='robot',
            name='max_bulk_trades',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of trades this robot can place in one bulk request (admin can change)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
