# Generated by Django 5.2.7 on 2026-08-24 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_robot_is_bulk_robot_robot_max_bulk_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrobot',
            name='win_rate',
            field=models.IntegerField(blank=True, help_text="Per-user win rate for this purchased robot (0-100). Leave blank to use the robot's default win_rate.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
