# Generated by Django 5.2.7 on 2026-09-05 17:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_userrobot_win_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EliteRobotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(default='5m', help_text='e.g. 1m, 5m, 15m, 1h, 4h', max_length=20)),
                ('stake', models.DecimalField(decimal_places=2, help_text='Minimum stake is 100 USD', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))])),
                ('target_profit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('50.00'))])),
                ('target_market', models.CharField(help_text='e.g. XAUUSD, EURJPY, BTCUSD', max_length=50)),
                ('config_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('code_used', models.BooleanField(default=False)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('run_started_at', models.DateTimeField(blank=True, null=True)),
                ('current_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status_message', models.CharField(blank=True, default='', max_length=255)),
                ('last_entry', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elite_configs', to='trading.robot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elite_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'robot')},
            },
        ),
    ]
