# Generated by Django 5.2.7 on 2026-09-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_eliterobotconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_elite_robot',
            field=models.BooleanField(default=False, help_text='Mark the SINGLE most expensive / Elite robot. Only one should be True.'),
        ),
    ]
