# Generated by Django 5.2.7 on 2026-09-05 18:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_robot_is_elite_robot'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliterobotconfig',
            name='last_credited_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
