# Generated by Django 5.2.7 on 2026-09-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_eliterobotconfig_last_credited_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliterobotconfig',
            name='target_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
