# Generated by Django 5.2.7 on 2026-09-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_eliterobotconfig_target_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrobot',
            name='is_setting',
            field=models.BooleanField(default=False, help_text='True once the user has successfully configured this robot as Elite. Stays True forever.'),
        ),
        migrations.AddField(
            model_name='userrobot',
            name='is_used',
            field=models.BooleanField(default=False, help_text='True after the user has started an Elite run. Hides the Settings button.'),
        ),
    ]
