# Generated by Django 5.2.7 on 2026-09-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_userrobot_is_setting_userrobot_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliterobotconfig',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Admin can pause a running Elite robot. Progress freezes until resumed.'),
        ),
        migrations.AddField(
            model_name='eliterobotconfig',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
