# Generated by Django 5.2.7 on 2026-09-14 13:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_eliterobotconfig_is_paused_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eliterobotconfig',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='True after successful M-Pesa payment for Elite Pro ($1500). Permanent.'),
        ),
        migrations.AddField(
            model_name='eliterobotconfig',
            name='pro_upgraded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EliteProPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='2547XXXXXXXX format', max_length=15)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=10)),
                ('amount_kes', models.PositiveIntegerField(help_text='KES amount sent to M-Pesa')),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='USD to KES rate used', max_digits=10)),
                ('merchant_request_id', models.CharField(blank=True, default='', max_length=64)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('mpesa_receipt', models.CharField(blank=True, default='', max_length=64)),
                ('result_code', models.CharField(blank=True, default='', max_length=10)),
                ('result_desc', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'STK Sent'), ('success', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_payments', to='trading.eliterobotconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elite_pro_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
